# This workflow will build a Java project with Maven
# For more information see: https://aberger.at/blog/2021/05/29/cloud-startproject.html

name: Build Application (master)

on:
  push:
    branches: [ develop ]

  workflow_dispatch:
    inputs:
      debug:
        description: enable tmate console debugging     
        required: false
        default: "disabled"
       
env:
  REGISTRY: ghcr.io
  DISTRIBUTION_FOLDER: target/distribution/docker
  GRAAL_VM_URL: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.0/graalvm-ce-java11-linux-amd64-21.3.0.tar.gz

jobs:
  appsrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - uses: actions/checkout@v2

    - name: cache maven repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
        key: ${{ runner.os }}-build-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-m2-

    - name: install graal vm
      run: |
        pwd
        ls -ld .
        curl --location --output graalvm.tgz ${{ env.GRAAL_VM_URL }}
        ls -l
        tar -xzf graalvm.tgz
        mv graalvm-* graalvm
        export GRAALVM_HOME=/opt/graalvm
        export PATH=$GRAALVM_HOME/bin:$PATH
        gu install native-image
        echo "GRAALVM_HOME=/opt/graalvm" >> $GITHUB_ENV
      working-directory: /opt

    - name: build supersonic native quarkus application
      run: |
        echo "graal home is $GRAALVM_HOME"
        mvn -Pnative -Dquarkus-profile=prod -Dbase.href="/" -B package

    - name: build appsrv docker image
      run: |
        docker build appsrv --tag ${{ env.REGISTRY }}/${{ github.repository }}-appsrv
      working-directory: distribution/${{ env.DISTRIBUTION_FOLDER }}        
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
    - name: push appsrv docker image
      run: |
        docker push ${{ env.REGISTRY }}/${{ github.repository }}-appsrv
      working-directory: distribution/${{ env.DISTRIBUTION_FOLDER }}        

  www:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cache node_modules (www)
      uses: actions/cache@v2
      with:
        path: './www//node_modules'
        key: ${{ runner.os }}-www-node-modules-v0.0.1-${{ hashFiles('./www/package.json') }}

    - name: install nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: install node dependencies
      run: |
        npm install
      working-directory: www

    - name: build web application
      run: npm run build
      working-directory: www

    - name: deploy to distribution folder
      run: |
        chmod +x copy-www.sh
        ./copy-www.sh
      working-directory: distribution

    - name: build nginx docker image
      run: |
        pwd
        ls -l
        docker build nginx --tag ${{ env.REGISTRY }}/${{ github.repository }}-nginx
      working-directory: distribution/${{ env.DISTRIBUTION_FOLDER }}

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
    - name: push nginx docker image
      run: |
        docker push ${{ env.REGISTRY }}/${{ github.repository }}-nginx
      working-directory: distribution/${{ env.DISTRIBUTION_FOLDER }}        
  deploy:
    needs: 
      - appsrv
      - www
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install ssh key
      uses: caberger/install-ssh-key@v1.0
      with:
        ssh-private-key:  ${{ secrets.SSH_SERVER_PRIVATE_KEY }}
        user: ${{ secrets.SERVER_USER }}
        server: ${{ secrets.SERVER }}
        alias: server
    - name: deploy to server  
      working-directory: distribution
      run: |
        ssh server "rm -rf ~/dist && mkdir -p ~/dist"
        scp -r *.sh server/ server:~/dist/
        scp ${{ env.DISTRIBUTION_FOLDER }}/docker-compose-production.yml server:~/dist
        ssh server "chmod +x ~/dist/*.sh"
        echo "running installation on server..."
        ssh server "cd ~/dist && sudo ./install.sh ${{ github.actor }} ${{ secrets.REGISTRY_ACCESS_TOKEN }} ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }} ${{ secrets.SERVER_USER }}"
        echo "done $(date)"
